### ISSUE TITLE
v1.4.1 building for NVIDIA GPU (Proprietary drivers)

### ISSUE THREAD

**Issue by jahanson** [siderolabs/talos#7155] opened 2023-04-29 12:36 UTC
## Bug Report

Using the documentation I can't build the `installer` package for v.1.4.1 with Nvidia GPU Proprietary Drivers.

### Description

I've been building in support for Nvidia GPU Proprietary drivers as per the documentation at https://www.talos.dev/v1.4/talos-guides/configuration/nvidia-gpu-proprietary/#upgrading-talos-and-enabling-the-nvidia-modules-and-the-system-extension since `v1.3.6` and I've had no problem up until `v1.4.1`. 

I can build the `kernel` and the `nonfree-kmod-nvidia` packages but I can't build the `installer` due to an error with the `${TARGETARCH}` arg I presume.

### Logs

```
sudo DOCKER_BUILDKIT=0 docker build --squash --build-arg RM="/lib/modules" -t ghcr.io/jahanson/installer:v1.4.1-nvidia .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  23.06MB
Step 1/4 : FROM scratch as customization
 ---> 
Step 2/4 : COPY --from=ghcr.io/jahanson/nonfree-kmod-nvidia:v1.4.1-8-g0657493 /lib/modules /lib/modules
 ---> Using cache
 ---> 00aec4afebfc
Step 3/4 : FROM ghcr.io/siderolabs/installer:v1.4.1
# Executing 7 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Running in 7a4f6706d947
xz: /usr/install//initramfs.xz: No such file or directory
The command '/bin/sh -c xz -d /usr/install/${TARGETARCH}/initramfs.xz     && cpio -idvm < /usr/install/${TARGETARCH}/initramfs     && unsquashfs -f -d /rootfs rootfs.sqsh     && for f in ${RM}; do rm -rfv /rootfs$f; done     && rm /usr/install/${TARGETARCH}/initramfs     && rm rootfs.sqsh' returned a non-zero code: 1


```

**Comment by smira** [comment] 2023-05-01 11:26
Duplicate of https://github.com/siderolabs/pkgs/issues/717

**Closed** 2023-05-01 12:07 UTC
