### ISSUE TITLE
Talos nodes bombarding DNS server with <control plane> hostname query with KubePrism enabled

### ISSUE THREAD

**Issue by nebula-it** [siderolabs/talos#7721] opened 2023-09-06 04:31 UTC
### Description
When KubePrism is enabled all talos nodes keeps querying DNS server every ~2seconds for <control plane> hostname.

### Logs
Not sure what logs would be helpful, but let me know and I can spin up new cluster and provide whatever is needed.

### Environment

- Talos version: `v1.5.1`
- Kubernetes version: [`v1.28.0`]
- Platform: Bare Metal and Hyper-V VMs mixed

**Comment by frezbo** [comment] 2023-09-06 06:41
duplicate of #7690

**Closed by frezbo** 2023-09-06 06:41 UTC
