### ISSUE TITLE
iscsi install fails on freshly added node

### ISSUE THREAD

**Issue by MansM** [siderolabs/talos#7807] opened 2023-09-29 16:04 UTC
## Bug Report
after having 1 master/1 node setup I am trying to add a second node.
1. create machine like proxmox guide
`
 talosctl apply-config --insecure --nodes 10.0.2.91 --file worker.yaml 
 talosctl -n 10.0.2.91 patch mc -p @patch.yaml
 talosctl -n 10.0.2.91  upgrade --image=ghcr.io/siderolabs/installer:v1.5.3

 `
patch.yaml
`
- op: add
  path: /machine/install/extensions
  value:
    - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
 `
### Logs
10.0.2.91: 2023/09/29 15:58:22 iscsid-wrapper: starting...
10.0.2.91: 2023/09/29 15:58:22 iscsid-wrapper: completed..., execing into iscsid
10.0.2.91: Error loading shared library libcrypto.so.3: No such file or directory (needed by /usr/local/sbin/iscsid)
10.0.2.91: Error loading shared library libcrypto.so.3: No such file or directory (needed by /usr/local/lib/libisns.so.0)
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get_size: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: DSA_generate_parameters_ex: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: ERR_reason_error_string: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get_bits: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: PEM_write_DSAparams: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_SignFinal: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: ERR_func_error_string: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: PEM_write_PUBKEY: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: i2d_DSA_PUBKEY: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: DSA_new: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_VerifyFinal: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_MD_CTX_new: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_free: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: DSA_generate_key: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_sha1: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: BN_GENCB_new: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: PEM_read_DSAparams: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_DigestUpdate: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: BN_GENCB_set_old: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get0_DSA: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: PEM_write_PrivateKey: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_MD_CTX_free: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: OPENSSL_init_crypto: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: BN_GENCB_free: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: DSA_free: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: PEM_read_PUBKEY: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_new: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_assign: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: d2i_DSA_PUBKEY: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: PEM_read_PrivateKey: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: DSA_get0_key: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: ERR_get_error: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get_base_id: symbol not found
10.0.2.91: Error relocating /usr/local/lib/libisns.so.0: EVP_DigestInit: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_sha256: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_MD_CTX_new: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_sha1: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_DigestUpdate: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_md5: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_MD_CTX_free: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: RAND_bytes: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_DigestInit_ex: symbol not found
10.0.2.91: Error relocating /usr/local/sbin/iscsid: EVP_DigestFinal_ex: symbol not found
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by frezbo** [comment] 2023-09-29 16:06
duplicate of https://github.com/siderolabs/extensions/issues/237

**Closed by frezbo** 2023-09-29 16:06 UTC
