### ISSUE TITLE
talosctl upgrade hangs on "waiting for actor ID"

### ISSUE THREAD

**Issue by sbogomolov** [siderolabs/talos#8931] opened 2024-06-22 09:47 UTC
I've tried upgrading from 1.7.4 to 1.7.5:
```
talosctl upgrade -n k8s-control-01 --image=factory.talos.dev/installer/92fca8fcdb4cb5dc69f52b84b77afb112a94c293daa261f49e6d2fa34dd06d78:v1.7.5
```

The upgrade process hangs on the first step:
```
WARNING: k8s-control-01: server version 1.7.4 is older than client version 1.7.5
◰ watching nodes: [k8s-control-01]
    * k8s-control-01: waiting for actor ID
```

I have tried rebooting the node and tried upgrading other nodes - same result. I have never had this problem before (I'm upgrading to every release).

- Talos version:
```
$ talosctl version -n k8s-control-01
Client:
	Tag:         v1.7.5
	SHA:         47731624
	Built:       
	Go version:  go1.22.4
	OS/Arch:     linux/amd64
Server:
	NODE:        k8s-control-01
	Tag:         v1.7.4
	SHA:         cb3a8308
	Built:       
	Go version:  go1.22.3
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version:
```
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1
```
- Platform: Proxmox

**Comment by frezbo** [comment] 2024-06-22 11:29
Duplicate of https://github.com/siderolabs/image-factory/issues/124

**Closed by frezbo** 2024-06-22 11:29 UTC
