### ISSUE TITLE
Talos Host DNS issue

### ISSUE THREAD

**Issue by raydenz** [siderolabs/talos#9191] opened 2024-08-17 13:47 UTC
hello,

I am running **Talos 1.7** on docker + cilium 1.14.8 :  1 control plane + 2 workers
I activated the HOST DNS feature (in docker mode talos ask me to do so)
```
machine:
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true

```
https://www.talos.dev/v1.7/talos-guides/network/host-dns/

## Bug Report
BUG : coredns pods can't reach host-dns
```
│ [ERROR] plugin/errors: 2 8548346077399810105.4798626237678217664. HINFO: read udp 10.244.1.237:47221->10.96.0.9:53: i/o timeout            │
│ [INFO] 10.244.1.55:36121 - 27217 "AAAA IN grafana.com. udp 40 false 1232" - - 0 2.000855639s                                               │
│ [ERROR] plugin/errors: 2 grafana.com. AAAA: read udp 10.244.1.237:43238->10.96.0.9:53: i/o timeout                                         │
│ [INFO] 10.244.1.55:57867 - 10742 "AAAA IN grafana.com. udp 40 false 1232" - - 0 2.001262023s                                               │
│ [ERROR] plugin/errors: 2 grafana.com. AAAA: read udp 10.244.1.237:43624->10.96.0.9:53: i/o timeout                                         │
│ [INFO] 10.244.1.55:56508 - 7879 "A IN grafana.com. udp 40 false 1232" - - 0 2.000621806s                                                   │
│ [ERROR] plugin/errors: 2 grafana.com. A: read udp 10.244.1.237:56486->10.96.0.9:53: i/o timeout  
```

i see a SVC named host-dns with this IP (10.96.0.9)
```
╰─ k get svc host-dns
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
host-dns   ClusterIP   10.96.0.9    <none>        53/UDP,53/TCP   21m
```
but there are no endpoints

- Talos version: 1.7
- Kubernetes version: [`kubectl version --short`]
- Platform: docker

**Comment by smira** [comment] 2024-08-19 08:50
As you don't specify the details, I'd assume it's a duplicate of https://github.com/siderolabs/talos/issues/8836#issuecomment-2158601983

**Closed by smira** 2024-08-19 08:50 UTC
