### ISSUE TITLE
talosctl cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by albgus** [siderolabs/talos#6125] opened 2022-08-22 13:05 UTC
### Description
When trying to run talosctl on a macOS machine you'll be faced with a pop-up stating "talosctl cannot be opened because the developer cannot be verified.". This only give the option of not running the tool or deleting it.

imo asking users to bypass security features that has been intentionally made hard to bypass is not a good solution.

Especially not for a software project that supposedly aims to provide a hardened product.

### Logs
![image](https://user-images.githubusercontent.com/4476818/185927451-ef025f83-d093-4263-a219-13b27421ed24.png)

### Environment

- Talos version: v1.1.0
- Kubernetes version: N/A
- Platform: macOS 12.5.1

**Comment by smira** [comment] 2022-08-22 18:34
This is the issue with the executable not being notarized by Apple. 

Notarization doesn't add much security in this particular, but nice to have feature. 

You can verify the downloaded executable against the `sha256` sums in the release, or even build it yourself from the source (builds are fully reproducible). This is much better guarantee than the notarization.

**Comment by smira** [comment] 2022-08-22 18:35
Duplicate of #2395

**Closed by smira** 2022-08-22 18:35 UTC
