### ISSUE TITLE
talosctl dashboard panic: /proc/cmdline: no such file or directory

### ISSUE THREAD

**Issue by chevdor** [siderolabs/talos#7349] opened 2023-06-09 14:52 UTC
### Description

Client:
	Tag:         v1.4.5
	SHA:         45679b0e
	Built:
	Go version:  go1.20.4
	OS/Arch:     darwin/amd64
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment] 2023-06-09 14:54
Duplicate of #7336. 

The fix will come in the next release

**Closed by smira** 2023-06-09 14:54 UTC
