### ISSUE TITLE
Please add hostname/IP to always present fields in logs.

### ISSUE THREAD

**Issue by zystem** [siderolabs/talos#8139] opened 2024-01-09 17:43 UTC
Regarding documentation (and that I see in actual logs) `msg, talos-level, talos-service, and talos-time fields are always present; there may be additional fields`.
But I do not want to run vector/filebeat/fluent-bit (for Talos logs) on each node (I already have promtail). I want to have a single point for the Talos logs collection. But in this case, I am unable to understand which line of logs is from which node. I need to extend logs with the source IP. But as I am using Cillium I have overlay IP (not node IP) so this data is useless.
Best practices (for example Syslog standard) say that if logs are sent via network sender should add the hostname to logs.
Please add hostname/IP to always present fields in logs.

**Comment by smira** [comment] 2024-01-18 18:53
Duplicate of #7356

**Closed by smira** 2024-01-18 18:53 UTC
