### ISSUE TITLE
Update the documentation to use new CPU type in Proxmox 8

### ISSUE THREAD

**Issue by sbogomolov** [siderolabs/talos#7421] opened 2023-06-28 20:05 UTC
## Feature Request

Update the [documentation](https://www.talos.dev/v1.4/talos-guides/install/virtualized-platforms/proxmox/) to use new CPU type in Proxmox 8.

### Description

In Proxmox 8 a new CPU type was added and made default: **x86-64-v2-AES**. With this CPU there is no need to add extra instructions via args. I think that the documentation should be updated with something like:

> If using Proxmox 8 or newer, there is no need to add extra args. The new default CPU type (x86-64-v2-AES) supports all necessary instructions.
> For more details: https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_8.0.

From [Proxmox 8 release notes](https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_8.0):
> Add virtual machine CPU models based on the [x86-64 psABI](https://gitlab.com/x86-psABIs/x86-64-ABI) Micro-Architecture Levels and use the widely supported x86-64-v2-AES as default for new VMs created via the web UI.

> The x86-64-v2-AES provides important extra features over the qemu64/kvm64 like SSE3, SSE4 and SSE4.1 and was slightly adapted to also provide AES support, improving performance of many computing operations dramatically.

**Comment by smira** [comment] 2023-06-29 13:13
Feels like duplicate of #7402

**Closed by smira** 2023-06-29 13:13 UTC
